/**
 * Build notes — one entry per shipped version, newest LAST, the Lodge Ops
 * convention carried over: never extend an already-shipped key, the appending
 * diff must show zero removed lines, and `node -e "import('./server/src/build-notes.mjs')
 * .then(m => console.log(m.BUILD_NOTES.length))"` must parse after every append.
 */

export const BUILD_NOTES = [
  {
    key: '0.1.0',
    version: '0.1.0',
    date: '2026-09-05T12:00:00+02:00',
    changes: [
      {
        headline:
          'The STO portal becomes its own product (Dave, 2026-09-05: “move the STO site to the LodgeITSTO repo”). Split out of the Lodge Ops repo, where it shipped as sto-portal/ + frontend/projects/sto-portal in Lodge Ops 1.3.54–1.3.55: the Specialist Tour Operators’ portal — sign in, a pinned command bar, New booking with the operator’s discounted plan card and the two-month availability calendar, Holds and Bookings with slide-outs, Account — and the small Node service that serves it and is the ONLY thing an operator’s browser talks to. Functionally identical to what Lodge Ops 1.3.55 shipped; the change is where it lives and how it is built and deployed.',
        detail:
          'LAYOUT: app/ is a standalone Angular 20 workspace (single project sto-portal, `npm run build` → app/dist/sto-portal/browser) carrying its OWN copies of the three Lodge Ops shared pieces it used (app/src/app/shared/standard-grid.component.ts, grid-sort.ts, slideout-exit.ts) and of Lodge Ops’ styles.scss (the Organic palette + oa-* vocabulary) — the portal must build without Lodge Ops; keep those in step by hand. server/src/server.mjs is the service (node built-ins only): serves the built app, signs every /api/lo/* call to Lodge Ops’ /api/sto-portal/* with the PORTAL KEY (X-Sto-Key / X-Sto-Ts / X-Sto-Sign, HMAC over ts.METHOD.path.sha256(body)) plus the user’s Bearer token, relays ONLY its allow-list, asks the Booking Engine (as engine client `sto`) for availability / a quote / the calendar only for a session Lodge Ops has vouched for (GET /me, remembered 5 min), rate-limits per client IP, and reports {ok, version, lodgeOps, engine} on /health. VERSION is read from a VERSION file beside server.mjs (installed by deploy.sh), else the repo root, else package.json. DEPLOY: deploy/deploy.sh (root, from a deploy-only clone at /root/BookingEngine/LodgeITSTO): git pull --ff-only, npm ci in app/ only when package-lock.json changed (sha256 stamp; FORCE_CI=1), ng build, rsync the build + server.mjs + package.json + VERSION into /opt/lodgeit-sto-portal, gates on /opt/lodgeit-sto-portal/.env (deploy/sto.env.example) and the unit (deploy/lodgeit-sto-portal.service, User=oase), restarts lodgeit-sto-portal and fails unless /health says ok, the right version, lodgeOps=true and engine=true. WIRING ONLY in the env: PORT, LISTEN_HOST, TRUSTED_PROXY, DIST_DIR, LODGEOPS_URL, STO_KEY, STO_SECRET, ENGINE_URL, CLIENT_KEY, CLIENT_SECRET, RATE_LIMIT, RATE_WINDOW_MS. VERIFIED on the Lodge Ops e2e rig (STO_DIR points at this checkout; case 95, 85 checks, incl. Chromium against this build).',
      },
    ],
  },
  {
    key: '0.1.1',
    version: '0.1.1',
    date: '2026-09-05T12:46:22+02:00',
    changes: [
      {
        headline:
          'The portal is configured from Lodge Ops, not from its .env (Dave, 2026-09-05: \u201cMove the Lodge Ops STO settings from .env to a settings and hub page\u201d). The environment keeps only the road to Lodge Ops \u2014 PORT, LISTEN_HOST, TRUSTED_PROXY, DIST_DIR, LODGEOPS_URL, STO_KEY, STO_SECRET (and CONFIG_PULL_MS). Which engine to ask, the engine client the portal signs as and its secret, the rate limit, session hours and the public address all come from Lodge Ops \u2192 Settings \u2192 STO Portal, pulled on boot and every minute; the portal reports a heartbeat back so that page shows it is up, which version, and whether it can see the engine.',
        detail:
          'server.mjs: ENGINE_URL, CLIENT_KEY, CLIENT_SECRET, RATE_LIMIT and RATE_WINDOW_MS are gone from the environment; a mutable cfg {engineUrl, clientKey, clientSecret, rateLimit, rateWindowMs, sessionHours, portalUrl, at} is filled by pullConfig() \u2014 GET /api/sto-portal/config on Lodge Ops, signed with the portal key like every other call \u2014 awaited before listen() and again every CONFIG_PULL_MS (default 60 000, floor 1 000); the last good answer is kept when Lodge Ops is away, and changes are logged (the secret only as \'rotated\'). engine() signs with cfg; allow() rate-limits with cfg; heartbeat() POSTs {version, uptimeSec, url: cfg.portalUrl, listen, engineReachable (GET <engine>/api/health = 200), configAt} to /api/sto-portal/heartbeat after every pull. /health now also carries configAt and engineUrl. deploy/deploy.sh no longer fails when the engine link is missing \u2014 it says where to set it (Settings \u2192 STO Portal). deploy/sto.env.example, README and CLAUDE.md rewritten for the new split. Requires Lodge Ops 1.3.57 (migration 390). VERIFIED on the Lodge Ops e2e rig: case 95 (config pull signed / unsigned, heartbeat, a client-secret rotation from Lodge Ops picked up on the next pull, the hub page in Chromium).',
      },
    ],
  },
  {
    key: '0.1.2',
    version: '0.1.2',
    date: '2026-09-05T14:46:52+02:00',
    changes: [
      {
        headline:
          'The portal sells on ONE channel and nothing else (Dave, 2026-09-05: \u201cThe STO booking site must only query availability and rates using the STO Channel\u201d). Every rate, every free-unit count and every calendar figure an operator sees now comes from the STO channel Lodge Ops assigns, asked of the Booking Engine in one signed call. The website\u2019s rate plans are no longer reachable from here at all, and with no channel assigned the portal quotes nothing and says the lodge has not finished setting it up \u2014 a silent fall back to the public price is exactly the failure this removes. Operators see one price card, named for their channel.',
        detail:
          'server.mjs: the pulled configuration gains channelId (Lodge Ops 1.3.58, GET /api/sto-portal/config), logged like the rest when it changes. NEW channelQuote({roomTypeIds, from, to, adults, children, infants, scan}) \u2014 POST /api/engine/rates/channel-quote (engine 0.1.83) signed as the portal\u2019s client, naming cfg.channelId; no channel returns 503 NO_CHANNEL with the operator-facing wording and never calls the engine. /api/engine/availability now derives its {suites: {id: unitsFree}} from a scan-declared channel quote with NO suites named (the engine answers for every suite with a root) and returns the channel beside it, replacing the raw /api/engine/rate-engine/availability read. /api/engine/quote returns {stayNights, channel, plans:[ONE card]} where the card carries the CHANNEL\u2019s name and its source plan\u2019s id \u2014 the app\u2019s existing plan-card rendering is unchanged, and a booking still names a plan Lodge Ops and the engine both know. /api/engine/calendar is rebuilt from channel quotes in 31-night chunks, each night\u2019s rate from the quote\u2019s nights and its free units from the quote\u2019s nightsFree, so the calendar has no second road to availability either. The three retired calls (/api/engine/rate-engine/availability and /api/engine/rates/quote) appear nowhere in the server any more. Requires Lodge Ops 1.3.58 and engine 0.1.83. VERIFIED on the Lodge Ops e2e rig (case 95, 98 checks): the channel named in availability and the quote, a third adult NOT carrying the website\u2019s additional-guest charge, and both Lodge Ops and the portal refusing to quote when the channel is unset.',
      },
    ],
  },
  {
    key: '0.1.3',
    version: '0.1.3',
    date: '2026-09-05T16:50:09+02:00',
    changes: [
      {
        headline:
          'Every rate the portal asks for now carries the operator\'s key, so the rate engine prices that operator itself \u2014 and the price card shows both figures (Dave, 2026-09-05: \u201cOn the portal when showing a rate total, so the STO discounted rate and below show in a smaller font the original rack rate with a strike through\u201d). The operator\'s price is the large figure; beneath it, smaller and struck through, the lodge\'s published rate with the percentage off. The same pairing appears on the booking summary and in each calendar cell. The key belongs to the SERVER: it signs the engine quote with it and strips it out of anything a browser sees.',
        detail:
          'server.mjs: the session vouch now remembers the operator\'s key from Lodge Ops\' /me (portalKey, Lodge Ops 1.3.59) and channelQuote() sends it as stoKey on every availability, quote and calendar call (engine 0.1.85). THE KEY NEVER REACHES A BROWSER \u2014 the /api/lo/ relay strips portalKey out of the /me answer on its way back, so the page holds the company and the discount percentage but nothing that names the operator to the engine. /api/engine/quote passes the engine\'s sto {applied, discountPct} through beside the one price card; /api/engine/calendar shows the operator\'s nightly figure as the cell\'s rate with the channel\'s own beside it as rack, both from the quote\'s stoTotalInclVat and totalInclVat. app: QuoteSuite gains sto {discountPct, rateTotal, vatTotal, grandTotal} and CalendarDay gains rack. New-booking prices from the ENGINE\'s operator figure (stoSum()) rather than multiplying the rack by a percentage locally \u2014 the local arithmetic survives only as a fallback for a quote with no operator figure. The card renders the operator\'s total in .nb-plan-total with the rack beneath in .nb-plan-rack as <s>\u2026</s> plus a \u201cn% off\u201d label; the booking summary\'s \u201cYour price\u201d gains the same struck-through rack line; a calendar cell shows the rack struck through under the nightly when the two differ. The gap between the struck figure and the \u201c% off\u201d label is a CSS margin, not a space in the template: Angular collapses whitespace between inline elements (preserveWhitespaces is off) and the first build shipped \u201cR13,800.0010% off\u201d \u2014 the e2e check now measures that gap so it cannot come back. Requires Lodge Ops 1.3.59 and engine 0.1.85. VERIFIED on the Lodge Ops e2e rig (case 95, 108 checks) including a Chromium check that the rack figure sits BELOW the price, in a smaller font, with line-through, and that /me through the portal carries no key.',
      },
    ],
  },
  {
    key: '0.1.4',
    version: '0.1.4',
    date: '2026-09-06T06:55:00+02:00',
    changes: [
      {
        headline:
          'What this rate includes, what comes back if it is cancelled, and a calendar you can click the stay out on (Dave, 2026-09-06 — the same three asks as Lodge Ops’ own New booking page, so the two look and behave alike). Each price card carries an “i” in its top right corner that opens what the rate includes and what it does not; the card also states the refund terms in the same sentence the booking website writes. In the availability calendar, clicking a night and then another moves the stay to those dates — either order — and Nights, the price card and the summary all follow. ALSO FIXED: every rate in that calendar read zero.',
        detail:
          'Pairs with Lodge Ops 1.3.60; no engine change. THE ZERO-RATE BUG: the calendar keyed each day’s rates by the CHANNEL’s id while the app looks a day’s rate up by the id its price card carries — the channel’s SOURCE PLAN. On the e2e rig the two happen to both be 1, which hid it completely; the merge now keys by planId || id, the same value the price card is given, and the e2e check reads the figure out of the cell rather than counting cells. A second bug in the same cell: the app was applying the operator’s discount to a rate the engine had already discounted, so a cell showed the discount twice — it now draws what the server sends. WHAT THIS RATE INCLUDES: the server pulls GET /api/engine/plan-inclusions (Lodge Ops’ own words, replicated to the engine), caches them five minutes and attaches the plan’s included/excluded to the one price card; QuoteSuite gains inclusionsAdded/inclusionsRemoved, and openInclusions() merges the plan’s list with the rule-driven changes for THIS stay (case-folded, removals win) so a rule that drops the spa credit strikes it through under “Not included”. The “i” is a SIBLING button of the card, never nested inside it — a button inside a button makes the whole card unclickable. REFUND TERMS: QuoteSuite gains refundable and refundLabel() is the booking site’s core.js sentence ported verbatim, so an operator and a guest never read different terms for the same rate; several suites that disagree say “Refund terms vary by suite”. CLICK THE STAY OUT: the calendar day cells are BUTTONS now (browser button styling reset back to the card look, past days disabled); the first click marks the first NIGHT and the hint changes, a second click on the last night sets check-in and check-out (the morning after the last night, so the outlined cells are exactly the nights paid for), the same night twice is a one-night stay, either order works. Escape closes the inclusions modal first, then the calendar. VERIFIED on the Lodge Ops e2e rig (case 95, 115 checks): 95.32b the plan’s inclusions and the refund policy on the quote, 95.92c the refund sentence on the card, 95.92d/e the modal and its ✕, 95.93 every requested night showing R4,140 over a struck-through R4,600 with “3 free”, 95.93b/c/d the two-click stay in both orders. Full suite green (531).',
      },
    ],
  },
  {
    key: '0.1.5',
    version: '0.1.5',
    date: '2026-09-06T08:10:00+02:00',
    changes: [
      {
        headline:
          'Three asks from Dave on 2026-09-06. A booking can no longer be started with half a guest: first name, last name, e-mail address, phone number and country are all required, and until every one of them is filled in BOTH \u201cHold for 24 hours\u201d and \u201cMake the booking\u201d stay asleep, with a line naming exactly what is still missing. Cancelling a hold now asks \u201cPlease add any note about the cancelation here\u201d and will not confirm until something is typed \u2014 so a released hold always carries a reason. And the home page gains two things: a \u201cNights booked\u201d card showing the room nights and the guests the operator has booked, and a two-month availability heat map of the guest suites, shaded from wide open to full, with \u2039 \u203a, Today, and a month picker.',
        detail:
          'Pairs with Lodge Ops 1.3.61 (migration 393); no engine change. REQUIRED GUEST FIELDS: new-booking gains guestMissing() (a typed list of the five, e-mail checked for shape rather than mere length), stayReady(), and canHold()/canBook() which both now require an empty missing list; the five labels carry a gold .nb-req asterisk and the .nb-need line reads them back in Dave\u2019s own words. The check is on the BUTTONS, not on submit \u2014 a disabled button cannot be talked past by a keyboard. THE CANCELLATION NOTE: the hold slide-out\u2019s Cancel no longer acts at once; it opens a panel with a textarea and a Confirm that stays disabled until the note has real characters, and the typed note is what is sent as the cancellation reason (the same field the lodge sees on the hold in Lodge Ops), so the portal and Lodge Ops always tell the same story about why the nights came back. NIGHTS BOOKED: Summary.bookings gains roomNights and guests from Lodge Ops (1.3.61), which multiplies each suite line by its UNITS \u2014 two Lagoons for three nights is six room nights, not three. THE HEAT MAP: a new server route GET /api/engine/heatmap?from&to walks the span in 31-night chunks (the engine\u2019s own scan limit), asks the STO channel with the operator\u2019s key, and sums nightsFree across every suite the channel sells into one figure per day; it returns free units only \u2014 how many units the lodge HAS is Lodge Ops\u2019 figure and the app already holds it in its catalogue (unitsTotal per suite), so nothing guesses a capacity from the busiest day it happened to see. The app draws this month and the next side by side, shadeFor() bucketing each day from open to full against that catalogue total, with a legend, \u2039 \u203a a month at a time, Today, and a month <input type=\'month\'> \u2014 all of which change WHAT is shown, never a Refresh of the same view. VERIFIED on the Lodge Ops e2e rig (case 95, 135 checks): 95.91b the Nights booked card against the database, 95.91c the two months and the shading, 95.91d \u2039 a month earlier, 95.91e the picker jumping and the engine re-asked, 95.93e\u2013h the five fields waking both buttons (a malformed e-mail counting as missing, the country last), 95.96b\u2013d the note panel, Confirm asleep until it is typed, and the note kept as the hold\u2019s reason. Full suite 550 passed with one unrelated timing failure in case 40 that passes 69/0 on its own.',
      },
    ],
  },
  {
    key: '0.1.6',
    version: '0.1.6',
    date: '2026-09-06T10:50:00+02:00',
    changes: [
      { headline: 'A stay is now clicked out as CHECK-IN and CHECK-OUT rather than as first and last night (Dave, 2026-09-06: \u201ctreat the earlier date as the check in date and the later date as the check out date\u201d) \u2014 on the availability calendar of BOTH new booking pages and on the STO portal\u2019s home-page heat map. Click two days in either order: the earlier one is check-in, the later one is check-out, and the nights outlined run from check-in to the day BEFORE check-out, because those are the nights that are paid for. Checking in and out on the same day is not a stay, so a second click on the same day is ignored and the page keeps asking. ALSO: two clicks on the STO portal\u2019s heat map now open a box offering \u201cCreate a booking for these dates\u201d, which opens the New booking page already on those dates.', detail: 'Pairs with Lodge Ops 1.3.63; no engine change. THE HEAT MAP BOOKS: the cells are BUTTONS now (browser button styling reset back to the card look, past days disabled), pickFrom/pickTo/pickHover hold the two clicks, and stay() turns them into {from, to, nights} plus the tightest night\u2019s free units read out of the heat map data already on the page \u2014 no second call to the engine to open the box. The box is a plain overlay with \u201cPick again\u201d, a \u2715 and a routerLink to /new carrying from and to; Escape and a click on the backdrop both clear the pick. NewBookingComponent reads those two query params in ngOnInit through ActivatedRoute.snapshot and applies them only when both are ISO dates and to > from \u2014 anything malformed is ignored and the page opens on its usual default rather than refusing to load. THE CONVENTION: pickDay() on the suite calendar matches Lodge Ops exactly \u2014 the two clicked days are check-in and check-out, sorted, the same day twice ignored, and the hover preview stopping the day before the pointer. VERIFIED on the Lodge Ops e2e rig (case 95, 152 checks): 95.91f one click marks check-in and asks for check-out with no box yet, 95.91g the same day twice ignored, 95.91h the box for a three-night stay with the three NIGHTS still marked, 95.91i the button carrying both dates, 95.91j the New booking page opening on those dates priced and ready with nothing typed, 95.93b/c/d the suite calendar under the new reading (one night at R4,140, and check-out clicked first reading the same).' },
    ],
  },
  {
    key: '0.1.7',
    version: '0.1.7',
    date: '2026-09-06T12:05:00+02:00',
    changes: [
      { headline: 'An operator can now put THEIR OWN LOGO on their portal (Dave, 2026-09-06: \u201callow them to set their logo by clicking on the avatar in the top left of the page\u201d) \u2014 click the avatar in the command bar, choose a picture, and it replaces the 7 Star mark for everyone at that operator. Their home page also gains a \u201cRevenue booked\u201d card: what they have actually booked, with the published figure beside it. AND the availability calendars now CLOSE the moment the check-out day is clicked (Dave: \u201cwhen the check out date is set, close the calendar\u201d), so the plans, the price and the summary underneath are what the eye lands on next.', detail: 'Pairs with Lodge Ops 1.3.64 (migration 395); no engine change. THE AVATAR SETS THE LOGO: .pb-mark is a BUTTON now and a SIBLING of the brand link \u2014 a button nested inside a link swallows the link \u2014 with a hidden file input beside it and a \u270e overlay on hover. The picture is shrunk in the BROWSER before it is ever sent: drawn onto a 256 px square canvas, LETTERBOXED rather than cropped (a logo cropped to a circle loses its wordmark) and kept as PNG so a cut-out background stays cut out, then POSTed to /api/lo/me/logo. A \u201cRemove logo\u201d button appears beside Account only once one is set. The portal server\u2019s relay allows me/logo through and gives THAT ONE PATH a 1 MB body cap while everything else stays at 64 KB \u2014 every other call an operator makes is a handful of fields. REVENUE BOOKED: a new home-page card reading bookings.liveValue with the live count, the rack figure when it differs, and what has been cancelled. THE CALENDAR CLOSES: NewBookingComponent.pickDay() calls closeCalendar() once the check-out click has set both dates, so the price card underneath is what you land on; reopen the calendar to change them. VERIFIED on the Lodge Ops e2e rig (case 95, 163 checks) including a Chromium check that the bar shows the operator\u2019s own picture, that the Revenue booked card matches the database to the cent, and that the calendar is gone after the second click.' },
    ],
  },
  {
    key: '0.1.8',
    version: '0.1.8',
    date: '2026-09-06T13:20:00+02:00',
    changes: [
      { headline: 'EVERY BOOKING AND EVERY HOLD NOW COMES WITH A GUEST BOOKING INFORMATION SHEET (Dave, 2026-09-06: \u201ccreate a booking information sheet in pdf ... that can be forwarded to the guest\u201d). A one-page PDF with the suites, the dates, the party, the money, the property\u2019s address and what the rate includes \u2014 made the moment the hold or booking is taken, ATTACHED to the e-mail the operator receives, FILED against the reservation in Lodge Ops, and downloadable from the booking and hold slide-outs on both sides. THE MONEY ON IT IS THE FULL RATE, never the operator\u2019s: their discount is their arrangement with the lodge and has no business on a page that goes to the guest. The operator\u2019s own logo (migration 395) prints at the top. Bookings made in LODGE OPS get the same sheet, on the lodge\u2019s own letterhead with no operator named.', detail: 'Pairs with Lodge Ops 1.3.65; no engine change. The hold slide-out and the booking slide-out each gain a \u201cGuest booking information (PDF)\u201d button that fetches the sheet THROUGH HttpClient as a blob \u2014 an <a href> carries no Authorization header, and the relay wants the session\u2019s Bearer token \u2014 then hands the browser the bytes under the file name Lodge Ops chose (read off the Content-Disposition), revoking the object URL on the next tick because revoking synchronously can beat the click. server.mjs: the relay allows holds/:id/sheet and bookings/:id/sheet, and those TWO paths go through a new callRaw()/lodgeOpsRaw() pair that keeps the answer as BYTES \u2014 decoding a PDF to utf8 the way every other answer is decoded would corrupt it \u2014 passing the content type, the length and the disposition straight back with no-store. Nothing else about the relay changed. VERIFIED on the Lodge Ops e2e rig (case 95, 172 checks): the PDF arrives with the %PDF- magic, the right file name, the stay on it, the FULL rate and not the operator\u2019s, the operator named, a hold\u2019s sheet saying it is provisional, and neither the public nor another operator able to fetch it.' },
    ],
  },
  {
    key: '0.1.9',
    version: '0.1.9',
    date: '2026-09-06T14:10:00+02:00',
    changes: [
      { headline: 'The guest\u2019s COUNTRY is a dropdown now, with that country\u2019s flag beside it (Dave, 2026-09-06: \u201cmake the country selector a dropdown and then show a mini flag of the country to the left of the dropdown\u201d) \u2014 on BOTH new booking forms, Lodge Ops\u2019 and the STO portal\u2019s. Eighty countries, the flag drawn to the left of the box, and it fills in the moment one is chosen. Nothing about what is STORED changed: the country is still kept as its name, exactly as every existing booking already holds it, so old rows read the same and the guest booking sheet prints the same.', detail: 'No migration, no backend change. NEW shared/countries.ts \u2014 a hand-kept list of eighty markets as {code, name} rather than a package: the whole thing is a few hundred bytes and a dependency for eighty rows would be worse than the rows. countryFlag() builds the flag from the ISO code\u2019s two REGIONAL-INDICATOR letters (ZA \u2192 \uD83C\uDDFF\uD83C\uDDE6): no image, no CDN, no request \u2014 a character the font draws. It resolves a stored value by NAME first and then by CODE, because rows written before this picker existed hold whatever a person typed, and returns a globe for anything it does not recognise rather than guessing. countryOptions() puts a stored value that is not on the list at the TOP instead of silently dropping it \u2014 an old row saying \u201cRepublic of South Africa\u201d must still show what it says, and choosing something else is what changes it. THE FLAG IS A SIBLING of the <select>, never inside it: a browser draws anything inside a select as option text. The select is bound with [ngModel]/(ngModelChange) as the house rule requires, and its value is the country NAME, which is what was stored before and what the guest sheet prints. e2e: 80.21g/h and 95.93g2/g3 \u2014 the field is a SELECT with more than fifty options including South Africa, the flag element is the FIRST child of its wrapper (so it really is to the left), it is empty until a country is chosen, and choosing South Africa puts \uD83C\uDDFF\uD83C\uDDE6 beside the dropdown. Case 80 is 45 checks, case 95 is 174. ALSO: 95.57 now waits for the engine to release the nights instead of reading them immediately \u2014 the release is asynchronous and the bare read had started failing intermittently. Not a product change, a test race.' },
    ],
  },
  {
    key: '0.1.10',
    version: '0.1.10',
    date: '2026-09-06T14:45:00+02:00',
    changes: [
      { headline: 'THE COUNTRY FLAGS ARE REAL PICTURES NOW \u2014 they were not showing (Dave, 2026-09-06, with a screenshot of the field reading \u201cEG\u201d where Egypt\u2019s flag should be). The first version drew the flag as an EMOJI, which works on a Mac and on a phone and NOT ON WINDOWS: Windows ships no flag glyphs at all, so a browser there draws the two letters of the country code instead. The flag is now a small SVG served by the application itself \u2014 no font to depend on, no CDN to reach, and the same picture on every machine.', detail: 'No migration, no backend change. The eighty flags the picker offers are VENDORED into public/flags/ as SVGs from flag-icons (MIT, https://github.com/lipis/flag-icons), with its licence and a README beside them saying only these markets are kept and that there is NO RUNTIME DEPENDENCY on the package \u2014 nothing was added to package.json, the files are simply in the repo. About 570 KB on disk across eighty files, but they are STATIC ASSETS, not bundle: a page fetches the one flag it is showing and the browser caches it, so the JavaScript is not a byte bigger. countries.ts: countryFlag() (which returned an emoji character) is replaced by countryCode() and countryFlagSrc(), the latter giving \u201c/flags/za.svg\u201d \u2014 ABSOLUTE, because both apps are served at the root with <base href=\"/\"> and a relative path would resolve against whatever route happens to be open. The template renders an <img class=\"nb-flag\"> with the country as its alt text, and a blank tile for a country the list does not know, so an unrecognised value gets an empty box rather than a broken-image icon. The flag remains a SIBLING of the <select>, never inside it. THE E2E NOW CHECKS THE PICTURE, not the character: it reads naturalWidth off the <img>, which is 0 on a src that failed, so a flag that does not actually load fails the case \u2014 the emoji version passed a text check while showing nothing, which is exactly how this shipped broken. 80.21g/h and 95.93g2/g3; case 80 is 45 checks, case 95 is 174.' },
    ],
  },
];
